#!/bin/bash
# Localhost WebSocket Agent Testing Guide

echo "=== Testing Warlock Agent on Localhost ==="
echo ""

PANEL_URL="http://127.0.0.1:3077"

echo "✓ Panel is already running on port 3077"
echo ""
echo "Option 1: Install via Web UI (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Open browser: $PANEL_URL"
echo "2. Navigate to Hosts > Add Host"
echo "3. Enter IP: 127.0.0.1"
echo "4. Click Add"
echo "5. Agent will auto-install!"
echo ""
echo "Option 2: Install Manually"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run these commands:"
echo ""
echo "  # Generate a test token"
echo "  TOKEN=\$(openssl rand -hex 32)"
echo ""
echo "  # Install agent"
echo "  cd /root/Warlock/agent"
echo "  sudo ./install.sh --panel-url $PANEL_URL --token \$TOKEN"
echo ""
echo "  # Note: You'll need to manually add the token to the database"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After Installation:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check agent status:"
echo "   systemctl status warlock-agent"
echo ""
echo "2. View agent logs:"
echo "   journalctl -u warlock-agent -f"
echo ""
echo "3. Check web UI:"
echo "   - Go to $PANEL_URL/hosts"
echo "   - Look for 127.0.0.1"
echo "   - Should show green 'Agent Connected' badge"
echo ""
echo "4. Monitor WebSocket connection in browser:"
echo "   - Open browser DevTools (F12)"
echo "   - Go to Network tab > WS filter"
echo "   - Should see active WebSocket connection"
echo ""
echo "5. Test command execution:"
echo "   - Any server operation will use WebSocket"
echo "   - Check panel logs for 'Executing via agent'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Troubleshooting:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If agent won't connect:"
echo "  journalctl -u warlock-agent -n 50"
echo ""
echo "If agent not installed:"
echo "  ls -la /opt/warlock-agent"
echo "  cat /etc/warlock/agent.conf"
echo ""
echo "To uninstall:"
echo "  cd /root/Warlock/agent"
echo "  sudo ./uninstall.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
